---
- name: "Add DVS in a DC {{ vc_server }}"
  vmware_dvswitch:
    hostname: "{{ vc_server.hostname }}"
    username: "{{ vc_server.username }}"
    password: "{{ vc_server.password }}"
    validate_certs: "{{ vc_server.validate_certs }}"
    datacenter_name: "{{ vc_server.datacentername }}"
    switch_name: "{{ vc_server.dv_switch.dv_switch_name }}"
    mtu: "{{ vm_dvs_mtu | int}}"
    uplink_quantity: "{{ vm_dvs_uplink_qty | int}}"
    discovery_operation: "{{ vm_dvs_discovery_options }}"
    discovery_proto: "{{ vm_dvs_dic_proto }}"
    state: present

- name: "Add DV-portgroup in vm dvs"
  vmware_dvs_portgroup:
    hostname: "{{ vc_server.hostname }}"
    username: "{{ vc_server.username }}"
    password: "{{ vc_server.password }}"
    validate_certs: "{{ vc_server.validate_certs }}"
    portgroup_name: "{{ vc_server.dv_port_group.dv_portgroup_name }}"
    switch_name: "{{ vc_server.dv_switch.dv_switch_name }}"
    vlan_id: "{{ vm_dvs_vlan_id | int }}"
    num_ports: "{{ vm_dvs_num_ports | int }}"
    portgroup_type: "{{ vm_dvs_pg_type }}"
    state: present
