---
- name: "Add nics to ContrailVM {{ esxi_host }}"
  vars: 
    vmname: "ContrailVM-{{ esxi_host.vcenter_server.datacentername }}-{{ esxi_host.name }}"
  vmware_guest:
    hostname: "{{ esxi_host.vcenter_server.hostname }}"
    username: "{{ esxi_host.vcenter_server.username }}"
    password: "{{ esxi_host.vcenter_server.password }}"
    validate_certs: "{{ esxi_host.vcenter_server.validate_certs }}"
    datacenter: "{{ esxi_host.vcenter_server.datacentername }}"
    cluster: "{{ esxi_host.cluster }}"
    name: "{{ esxi_host.contrail_vm.name | default (vmname) }}"
    networks:
      - name: "{{ std_pg_name }}"
        mac: "{{ esxi_host.contrail_vm.mac }}"
      - name: "{{ esxi_host.vcenter_server.dv_port_group.dv_portgroup_name }}"
  async: 3600
  poll: 0
  register: add_nic_result

- name: "Save add_nic task results {{ add_nic_result }} {{ esxi_host }} {{ vmname }}"
  set_fact:
    nics_added: "{{ nics_added | default ([]) + [add_nic_result] }}"
