---
- name: "Add nics to ContrailVM {{ esxi_host }}"
  vars: 
    vmname: "ContrailVM-{{ esxi_host.vcenter_server.datacentername }}-{{ esxi_host.name }}"
  vmware_guest:
    hostname: "{{ esxi_host.vcenter_server.hostname }}"
    username: "{{ esxi_host.vcenter_server.username }}"
    password: "{{ esxi_host.vcenter_server.password }}"
    validate_certs: "{{ esxi_host.vcenter_server.validate_certs }}"
    datacenter: "{{ esxi_host.vcenter_server.datacentername }}"
    cluster: "{{ esxi_host.cluster }}"
    name: "{{ esxi_host.contrail_vm.name | default (vmname) }}"
    state: poweredon
  async: 3600
  poll: 0
  register: res

- name: "Save add_nic task results {{ add_nic_result }} {{ esxi_host }} {{ vmname }}"
  set_fact:
    powerd_on: "{{ powerd_on | default ([]) + [res] }}"
