---
# Setup repo for upgrade_kernel to find the kernel packages
# This repo needs to be setup only for Debian/RedHat cases where a separate repo container is not provided

- include: host.yml
  tags: [always]
  when:
    - "'contrail-repo' not in groups"
    - "'kubernetes-contrail-controllers' not in group_names"

- name: Check if correct kernel package is already installed
  command: "dpkg-query -l linux-headers-{{ kernel_version }}"
  register: kernel_upgrade_query
  ignore_errors: yes
  failed_when: "'FAILED' in kernel_upgrade_query.stderr"

- name: Set kernel_upgraded flag for compute provision to use
  set_fact:
      kernel_upgraded: true
  when: kernel_upgrade_query.stderr.find('no packages found') != -1

- include: install.yml
  when: kernel_upgrade_query.stderr.find('no packages found') != -1

- include: configure.yml
  when: kernel_upgrade_query.stderr.find('no packages found') != -1

- include: reboot.yml
  when: kernel_upgrade_query.stderr.find('no packages found') != -1
