---
- name: ceph pool vars
  debug:
    msg:
      - "fsid        = {{ storage_ceph_config['fsid'] }}"
      - "mon_key     = {{ storage_ceph_config['mon_key'] }}"
      - "osd_key     = {{ storage_ceph_config['osd_key'] }}"
      - "adm_key     = {{ storage_ceph_config['adm_key'] }}"
      - "osd_info    = {{ storage_ceph_config['osd_info'][ansible_hostname]['osd_info'] }}"
      - "pool_secret = {{ storage_ceph_config['pool_secret'] }}"
      - "ceph_hostip_list {{ ceph_controller_list }}"
      - "ceph_hostname_list {{ ceph_hostname_list }}"
  when: storage_ceph_config is defined

- debug:
    msg:
      - "item {{ item }} "
  with_items: "{{ disk_info }}"

