---
- name: Install contrail storage packages
  apt: name={{ item }} state=installed force=yes
  with_items:
    - contrail-storage

- name: create a symlink from /bin/true to /sbin/chkconfig
  file: src=/bin/true dest=/sbin/chkconfig state=link
