---
- name: Add contrail apt repository
  apt_repository:
    repo: "deb {{ contrail_apt_repo }} ./"
    state: present
  register: apt_repo_added
  when: contrail_apt_repo is defined
  ignore_errors: yes

- name: Allow unauthenticated packages for contrail packages to work
  copy: content='APT::Get::AllowUnauthenticated "true";' dest=/etc/apt/apt.conf.d/99allowunauth

- name: Pin contrail apt repo "contrail" release to priority 999
  template: src=apt-preferences.j2 dest=/etc/apt/preferences.d/contrail_repo.pref

- name: Run apt-get update
  apt: update_cache=yes
  when: apt_repo_added.get('changed',false)
  ignore_errors: yes
