---
#- name: Read facts from openstack/controller
#  include_role: name=openstack/controller tasks_from=facts
#
- include: install.yml
  when: tsn_node != True

- include: configure.yml
  when: tsn_node != True
