---
- include: puppet.yml
  when: install_puppet

- name: Run commands to setup NTP
  shell: "{{ item }}"
  with_items:
    - "service ntp stop"
    - "ntpdate {{smgr_ip}}"
    - "mv /etc/ntp.conf /etc/ntp.conf.orig"
    - "touch /var/lib/ntp/drift"
  when: smgr_ip != ansible_default_ipv4.address

- name: Create ntp.conf from template
  template: src=templates/ntp.conf.j2 dest=/etc/ntp.conf
            owner=root group=root mode=0644
  notify:
    - restart ntp
  when: smgr_ip != ansible_default_ipv4.address

- name: Blacklist mei and mei_me kernel modules
  lineinfile:
    path: "{{item.key}}"
    line: "{{item.value}}"
    create: yes
  with_dict:
    /etc/modprobe.d/blacklist.conf: "blacklist mei"
    /etc/modprobe.d/blacklist.conf: "blacklist mei_me"
    /etc/modprobe.d/mei.conf: "blacklist mei"
    /etc/modprobe.d/mei_me.conf: "blacklist mei_me"
    /etc/modprobe.d/mei.conf: "install mei /bin/true"
    /etc/modprobe.d/mei_me.conf: "install mei_me /bin/true"

- name: Copy the interface setup and static route setup scripts
  copy:
    src: "{{ item.key }}"
    dest: "{{ item.value }}"
    owner: root
    group: root
    mode: 0644
  with_dict:
    /var/www/html/kickstarts/interface_setup.py: "/root/interface_setup.py"
    /var/www/html/kickstarts/staticroute_setup.py: "/root/staticroute_setup.py"
    "/var/www/html/contrail/config_file/{{ansible_hostname}}.sh": "/etc/init.d/{{ansible_hostname}}.sh"

- name: Run commands to setup NTP and run interface setup and static route scripts
  shell: "{{ item }}"
  with_items:
    - "chmod +x /etc/init.d/{{ansible_hostname}}.sh"
    - "/etc/init.d/{{ansible_hostname}}.sh"
