---
- name: sm_status_report - preconfig_started
  debug:
    msg: "preconfig_started"

- name: Update /etc/hosts with Server Manager IP
  lineinfile:
    dest: /etc/hosts
    regexp: '^{{ smgr_ip }} server_manager'
    line: '{{ smgr_ip }} server_manager'
    state: present

- name: Update /etc/hosts with Servers Own Hostname and Domain
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{item}}$'
    line: '{{hostvars[item].ansible_default_ipv4.address}} {{hostvars[item].ansible_hostname}}.{{domain_name}} {{hostvars[item].ansible_hostname}}'
    state: present
  with_items: '{{groups.all}}'
  when: domain_name != ""

- include: install/{{ ansible_os_family }}.yml
  tags: [preconfig, package]

- include: provision/main.yml
  tags: [preconfig, provision]

- name: sm_status_report - preconfig_completed
  debug:
    msg: "preconfig_completed"
