---
- name: sm_status_report - preconfig_started
  debug:
    msg: "preconfig_started"

- name: fail in case domain name is not specified
  fail: msg="Cluster domain name is mandatory"
  when: domain_name == ""

- name: Update /etc/hosts with Servers Own Hostname and Domain
  lineinfile:
    dest: /etc/hosts
    regexp: '^{{hostvars[item].ansible_default_ipv4.address}}'
    line: '{{hostvars[item].ansible_default_ipv4.address}} {{hostvars[item].ansible_hostname}}.{{domain_name}} {{hostvars[item].ansible_hostname}}'
    state: present
  with_items: '{{groups.all}}'
  when: hostvars[item].ansible_default_ipv4.address != smgr_ip

- name: Update /etc/hosts with Server Manager IP
  lineinfile:
    dest: /etc/hosts
    regexp: '^{{hostvars[item].ansible_default_ipv4.address}}'
    line: '{{hostvars[item].ansible_default_ipv4.address}} {{hostvars[item].ansible_hostname}}.{{domain_name}} {{hostvars[item].ansible_hostname}} server_manager puppet'
    state: present
  with_items: '{{groups.all}}'
  when: hostvars[item].ansible_default_ipv4.address == smgr_ip

- include: install/{{ ansible_os_family }}.yml
  tags: [preconfig, package]

- include: provision/main.yml
  tags: [preconfig, provision]

- name: sm_status_report - preconfig_completed
  debug:
    msg: "preconfig_completed"
