---

- name: Common system settings on base hosts
  hosts: contrail-compute

  # docker_required is set to true if the node is running atleast one of
  # contrail-controller, contrail-analytics, contrail-analyticsdb, contrail-lb,
  # contrail-compute in 'container' mode.
  # In other words: set to false on standalone bare_metal computes
  # NOTE: Change here if you are adding a new group in the inventory that needs
  # to avoid installing docker-engine
  pre_tasks:
    - name: Set flag to decide if docker is required
      set_fact:
        docker_required: "{{ false if 'contrail-compute' in group_names and \
                          contrail_compute_mode != 'container' and \
                          'contrail-controllers' not in group_names and \
                          'contrail-analytics' not in group_names and \
                          'contrail-analyticsdb' not in group_names and \
                          'contrail-lb' not in group_names and \
                          'ceph-controller' not in group_names else \
                          true }}"
        provision_type: "{{ provision_type | default('') }}"

- name: Call Common Code
  hosts: all
  roles:
    - name: Run common code
      role: common

- name: Run the common task to create list
  hosts: all
  tasks:
    - include_role: 
       name: common
       tasks_from: create_list_facts

- name: Setup compute node
  hosts: contrail-compute
  roles:
    #- name: Run common code
    #  role: common
    - name: "Setup openstack compute in case of openstack {{ compute_list }}"
      role: openstack/compute
      tags: [openstack.compute]
      when:
        - cloud_orchestrator       == "openstack"
        - enable_openstack_compute is defined
        - compute_not_on_esxi      is defined
        - enable_openstack_compute == true
        - compute_not_on_esxi      == true

    - name: Setup baremetal agent
      role: contrail/bare_metal_agent
      tags: [contrail.bare_metal_agent]
      when:
        - contrail_compute_mode == 'bare_metal'
        - provision_type != 'contrail_cloud'

- name: Register roles with controller API
  hosts: contrail-controllers
  roles:
    - name: Register analytics, analyticsdb and agent with controller API
      role: contrail/register
      tags: [contrail.register]
      when: cloud_orchestrator == 'openstack' or cloud_orchestrator == 'vcenter'

- name: Reboot compute nodes
  hosts: contrail-compute
  post_tasks:

    - name: Reboot node
      shell: sleep 15 && /etc/contrail/contrail_reboot
      async: 20
      poll: 0
      sudo: true
      ignore_errors: true
      when:
        - (contrail_compute_mode == 'bare_metal')
        - (provision_type == '')

    - name: Reboot node having container
      shell: sleep 15 && docker exec -i agent /etc/contrail/contrail_reboot
      async: 20
      poll: 0
      sudo: true
      ignore_errors: true
      when:
        - (contrail_compute_mode == 'container')
        - (provision_type == '')

    # Skip this task from being run on the SM Lite node itself to avoid timing issues with Reboot
    - name: Waiting for server to come back
      local_action: wait_for port=22 host={{ inventory_hostname }} state=started delay=30 timeout=600
      sudo: false
      when:
        - (contrail_compute_mode == 'bare_metal' or contrail_compute_mode == 'container')
        - (provision_type == '')
