---
- name: include OS family specific package dependencies
  include: "{{item}}"
  with_first_found:
    - files:
      - "install/{{ ansible_os_family }}.yml"
      skip: true
  tags: [package]

- name: Create directory /var/log/contrail
  file: path=/var/log/contrail state=directory
  tags: [package, install]

# Call node/contrailctl_facts.yml which simulate contrailctl effect
# to rewrite variables
# NOTE: This is only required for non-container code.
# For containers, contrailctl does the job
- name: Read contrailctl like variables
  include_role: name=node tasks_from=contrailctl_facts
