---
- name: include OS family specific package dependencies
  include: "{{item}}"
  with_first_found:
    - files:
      - "install/{{ ansible_os_family }}.yml"
      skip: true
  tags: [package]

- name: Create directory /var/log/contrail
  file: path=/var/log/contrail state=directory
  tags: [package, install]
