---
- name: sm_status_report - analytics_started                                                                                                                                   
  debug:
    msg: "analytics_started"

- name: Copy contrail analytics image
  copy:
    src: "{{ docker_image_load_path }}/{{ contrail_analytics_image_archive }}"
    dest: "/tmp/{{ contrail_analytics_image_archive }}"
  when: docker_registry is not defined or load_contrail_analytics_image is defined

- name: "Load contrail analytics image"
  docker_image:
    name: contrail-analytics
    tag: "{{ contrail_version }}"
    timeout: "{{ container_image_load_timeout }}"
    load_path: "/tmp/{{ contrail_analytics_image_archive }}"
  when: docker_registry is not defined  or load_contrail_analytics_image is defined

- name: Configure contrailctl/analytics.conf
  include: "contrailctl/analytics/{{ contrailctl_config_mode }}.yml"

# Copy SSL certs to container
- include: copy_ssl_certs.yml

- name: "Start contrail analytics container"
  docker_container:
    name: analytics
    image: "{{ analytics_image }}"
    privileged: true
    network_mode: host
    state: started
    pull: "{{ always_pull_image }}"
    tty: true
    restart_policy: unless-stopped
    capabilities:
      - AUDIT_WRITE
    volumes: "{{ contrail_analytics_volumes }}"
