---
# Copy SSL CA Cert onto Container/BareMetal

- name: Create SSL Cert dir on container
  file: path="{{ ssl_certs_dir }}" state=directory
  when: ssl_certs_supplied

- name: Copy SSL CA Cert file for use by container
  copy: src={{ item.src}} dest={{ item.dest }}
  with_items:
    - { src: "{{ ssl_certs_src_dir }}/ca-cert.pem", dest: "{{ ssl_ca_cert_path }}" }
  when: ssl_certs_supplied

- name: Copy cert files onto container
  copy: src={{ item.src}} dest={{ item.dest }}
  with_items:
    - { src: "{{ ssl_certs_src_dir }}/{{ ansible_hostname }}.pem", dest: "{{ ssl_cert_path }}"}
    - { src: "{{ ssl_certs_src_dir }}/{{ ansible_hostname }}-privkey.pem", dest: "{{ ssl_cert_key_path }}" }
  when: ssl_certs_supplied

- name: Copy toragent cert files onto container/BareMetal
  vars:
      tor_list: "{{ tor_agent.get(ansible_default_ipv4.address) }}"
  copy: src="{{ tor_ssl_certs_src_dir }}/tor.{{ ansible_hostname }}.{{ item.tor_agent_id }}.cert.pem" dest="{{ssl_tor_certs_dir}}/tor.{{ item.tor_agent_id }}.cert.pem"
  when: ssl_certs_supplied
  when: item
  with_items: "{{ tor_list }}"

- name: Copy toragent private files onto container/BareMetal
  vars:
      tor_list: "{{ tor_agent.get(ansible_default_ipv4.address) }}"
  copy: src="{{ tor_ssl_certs_src_dir }}/tor.{{ ansible_hostname }}.{{ item.tor_agent_id }}.privkey.pem" dest="{{ssl_tor_private_dir}}/tor.{{ item.tor_agent_id }}.private.pem"
  when: ssl_certs_supplied
  when: item
  with_items: "{{ tor_list }}"
