---
# Copy SSL CA Cert onto Container/BareMetal

- name: Create SSL Cert dir on container
  file: path="{{ ssl_certs_dir }}" state=directory
  when: ssl_certs_supplied

- name: Copy SSL CA Cert file for use by container
  copy: src={{ item.src}} dest={{ item.dest }}
  with_items:
    - { src: "{{ ssl_certs_src_dir }}/ca-cert.pem", dest: "{{ ssl_ca_cert_path }}" }
  when: ssl_certs_supplied

- name: Copy cert files onto container
  copy: src={{ item.src}} dest={{ item.dest }}
  with_items:
    - { src: "{{ ssl_certs_src_dir }}/{{ ansible_hostname|lower }}.pem", dest: "{{ ssl_cert_path }}"}
    - { src: "{{ ssl_certs_src_dir }}/{{ ansible_hostname|lower }}-privkey.pem", dest: "{{ ssl_cert_key_path }}" }
  when: ssl_certs_supplied

- name: Get the tor_agent_list
  set_fact:
    tor_agent_list: "{{ tor_agent.get(ansible_default_ipv4.address) }}"

- name: Copy toragent cert files onto container/BareMetal
  copy: src="{{ tor_ssl_certs_src_dir }}/tor.{{ item.tor_agent_id }}.cert.pem" dest="{{ssl_tor_certs_dir}}/tor.{{ item.tor_agent_id }}.cert.pem"
  when: item and tor_ssl_certs_supplied and item.tor_ovs_protocol == 'pssl'
  with_items: "{{ tor_agent_list }}"

- name: Copy toragent private files onto container/BareMetal
  copy: src="{{ tor_ssl_certs_src_dir }}/tor.{{ item.tor_agent_id }}.privkey.pem" dest="{{ssl_tor_private_dir}}/tor.{{ item.tor_agent_id }}.private.pem"
  when: item and tor_ssl_certs_supplied and item.tor_ovs_protocol == 'pssl'
  with_items: "{{ tor_agent_list }}"

- name: Copy SSL CA Cert file for toragent
  copy: src="{{ tor_ssl_certs_src_dir }}/ca-cert.pem" dest="{{ ssl_tor_certs_dir }}/tor-ca-cert.pem"
  when: item and tor_ssl_certs_supplied and item.tor_ovs_protocol == 'pssl'
  with_items: "{{ tor_agent_list }}"
