---

# Get the base ip of the configured cluster private network.
- set_fact: cluster_private_base_ip="{{ nested_cluster_private_network.split('/')[-2] }}"
- set_fact: cluster_private_base_ip_int="{{ cluster_private_base_ip|ipaddr('address')|ipaddr('int') }}"

# Start ip addr assignment from base + 1
- set_fact: cluster_private_base_ip_int="{{ cluster_private_base_ip_int|int+1 }}"

#
# Iterate through list of contollers and allocate private IP's for each
# from the configured cluster private subnet.
#
# The controller IP to its allocated cluster-private IP is cached in a
# dictionary for later use.
#
- name: Create dictionary of link local controller IPs to their fabric controller IPs.
  set_fact:
    cluster_private_base_ip_int: "{{ cluster_private_base_ip_int|int+1 }}"
    controller_pvt_ip_dict: "{{ controller_pvt_ip_dict|default({}) | \
        combine( {item: cluster_private_base_ip_int|ipaddr} ) }}"
  with_items: "{{ groups['kubernetes-contrail-controllers'] | default([]) }}"

# Construct the list of generate controller IPs.
- name: Create list of link local controller IPs.
  set_fact:
    controller_ll_ip_list: "{{ controller_ll_ip_list | default([]) + \
        [item.value] }}"
  with_dict: "{{ controller_pvt_ip_dict }}"
  when: nested_mode is defined

#
# Allocate private IPs for misc services.
#

# Start ip addr assignment from base + 100
- set_fact: cluster_private_base_ip_int="{{ cluster_private_base_ip|ipaddr('address')|ipaddr('int') }}"
- set_fact: cluster_private_base_ip_int="{{ cluster_private_base_ip_int|int+100 }}"

# Allocate private IP for authentication(keystone) service.
- name: Allocate keystone link local ip.
  set_fact:
    cluster_private_base_ip_int: "{{ cluster_private_base_ip_int|int+1 }}"
    keystone_link_local_ip: "{{ cluster_private_base_ip_int|ipaddr('address') }}"

# Allocate private IP for vrouter.
- name: Allocate vrouter agent link local ip.
  set_fact:
    cluster_private_base_ip_int: "{{ cluster_private_base_ip_int|int+1 }}"
    vrouter_agent_link_local_ip: "{{ cluster_private_base_ip_int|ipaddr('address') }}"

#
# From now on, the config servers should be referred to by their generated
# linkloca/private IP's. NAT the config server IPs to their linklocal/private
# IPs.
#
- name: NAT config_server_list_derived to its linklocal IP.
  set_fact:
      config_server_list_derived_tmp: "{{ config_server_list_derived_tmp | default([]) + [controller_pvt_ip_dict[item]] }}"
  with_items: "{{ groups['kubernetes-contrail-controllers'] | default([]) }}"
- set_fact: config_server_list_derived="{{ config_server_list_derived_tmp }}"
- set_fact: controller_ip_key="{{ groups['kubernetes-contrail-controllers'][0] if controller_ip|default("") == "" else controller_ip }}"
- set_fact: controller_ip="{{ controller_pvt_ip_dict[controller_ip_key] }}"
- set_fact: config_ip_key="{{ groups['kubernetes-contrail-controllers'][0] if config_ip|default("") == "" else config_ip }}"
- set_fact: config_ip="{{ controller_pvt_ip_dict[config_ip_key] }}"
