---
- name: Parse vgw configuration
  set_fact:
    vgw_public_subnet_list: "{{ vgw_public_subnet_list + [ item.value.ipam_subnets ] }}"
    vgw_public_vn_name_list: "{{ vgw_public_vn_name_list + [ item.value.vn ] }}"
    vgw_intf_list: "{{ vgw_intf_list + [ item.key ] }}"
  with_dict: "{{ vgw_config_compute }}"

- name: Parse vgw gateway_routes
  set_fact:
    vgw_gateway_route_list: "{{ vgw_gateway_route_list + [ item.value.gateway_routes ] if 'gateway_routes' in item.value.keys() else vgw_gateway_route_list + [ '[]' ] }}"
  with_dict: "{{ vgw_config_compute }}"
  when:
    - item
